### ISSUE TITLE
Problem with showing feedback within IntelliJ

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#1011]
Observed behavior: nothing happens when the user tries to open feedback in IntelliJ.

Opening the same feedback in a browser works as it should.

**Comment by OlliKiljunen** [comment]
Apparently, this does not happen always. Juha was not able to reproduce the bug; all worked correctly for him. The situation calls for further investigation...

**Comment by Taikelenn** [comment]
I was only able to reproduce it inside the "runIde" task; works fine on normal IntelliJ
