### ISSUE TITLE
More descriptive error message when user is not enrolled

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#1047]
Otto said in Slack:
> If the student opens O1 in intelliJ using their A+ credentials but has not enrolled in A+ the plugin says there is a network error.

The API response in the case seems to be 403 Forbidden with the following payload:
```json
{
    "detail": "You do not have permission to perform this action."
}

```

We could show a message like: *Could not access the course. Server responded: "&lt;the message from the HTTP response&gt;" Please make sure you've enrolled in the course and have access to it in A+.*

**Comment by jaakkonakaza** [comment]
If the user is not enrolled, a message is shown in the OverviewView telling the user they are not enrolled and to check the course page. The user can then press a refresh button, which will load the course if the user is enrolled
