### ISSUE TITLE
A+ Courses project template should not appear in new module creation

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#1048]
Related to fixed issue #867.

Ideally, A+ Courses project should only appear when creating a new project, not when creating a new module.

Based on our previous investigation, it seems that IntelliJ does not, however, support such distinction.

As a a workaround (kind of) we could make it so that it is not the choice selected by default. That could make it a bit less confusing for the students.

**Comment by Taikelenn** [comment]
I opened a community question https://intellij-support.jetbrains.com/hc/en-us/community/posts/13867414023058-Custom-ModuleBuilder-only-for-new-projects-not-modules for some advice from the JetBrains team

**Comment by jaakkonakaza** [comment]
The builder is not shown if the action launching the dialog contains "Module"
