### ISSUE TITLE
Don't use deprecated `ScalaActionUtil.enablePresentation` and `disablePresentation`

### ISSUE THREAD

**Issue by unkarjedy** [Aalto-LeTech/aplus-courses#1083]
`org.jetbrains.plugins.scala.actions.ScalaActionUtil#enablePresentation` / `org.jetbrains.plugins.scala.actions.ScalaActionUtil#disablePresentation` 
helper methods were deprecated in Scala Plugin 2023.2.

I am going to remove them in 2024.1

Please make sure you don't use them in https://github.com/Aalto-LeTech/aplus-courses/blob/7b801118d3b994e0871796c9707373eb81531285/src/main/scala/fi/aalto/cs/apluscourses/intellij/actions/ReplAction.scala#L37C7-L37C22

Use `com.intellij.openapi.actionSystem.Presentation#setEnabledAndVisible` instead

**Comment by OlliKiljunen** [comment]
Thank you for noticing us! We will follow your instructions and remove those references. :+1:
