### ISSUE TITLE
Show better message to students not enrolled on courses

### ISSUE THREAD

**Issue by jaakkonakaza** [Aalto-LeTech/aplus-courses#1133]
<img width="613" alt="image" src="https://github.com/user-attachments/assets/ff1bed22-3efe-4353-95bc-915d1936a9cb">

Currently courses that do not have a public /api/v2/courses/$id endpoint show the message correctly but since it is public for O1, a generic network error message is shown.

`/api/v2/users/me` could be checked for enrollment, but since it does not show the course for TAs they would not be able to access the course. After [this issue on aplus](https://github.com/apluslms/a-plus/issues/1397) is fixed we can use the `users/me` endpoint

**Comment by oseppala** [comment]
Another possible case is that the A+ token has been changed. The message could also say "... or you have created a new A+ token"
