### ISSUE TITLE
collapsible "Modules" and "Exercises"

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/aplus-courses#269]
so the idea is quite simple, when 2-clicking on the e.g. "Modules" subtab, it collapses and gives all the space to "Exercises"
before:
![before_collapse](https://user-images.githubusercontent.com/9991098/88897116-7416ef00-d253-11ea-8080-ef70e5d1b003.PNG)
after (but without that scope behind the red "zig-zagged" line in between)
![after_collapse](https://user-images.githubusercontent.com/9991098/88897129-79743980-d253-11ea-8af3-52a11d6d568c.PNG)

**Comment by nikke234** [comment]
Good idea! I wonder if it's more intuitive the other way around though: double-clicking on modules expands (instead of collapses) modules

**Comment by superseacat** [comment]
this is just a crude idea, the benefit I see is saving space, so any approach will do
