### ISSUE TITLE
dependencies updating when the Module is updated

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/aplus-courses#354]
as per quick testing on **RoboTribes**, the dependencies do not get updated (**Robots**) when the module is updated, thus they should.

* [ ] what if the updatable deps have changes in it (roll-back)?
* [ ] all or none approach?

**Comment by superseacat** [comment]
go down all the way into the rabbits hole and traverse the deps tree and check if possible etc.

**Comment by OlliKiljunen** [comment]
"all or none approach" is probably the way to go
