### ISSUE TITLE
Refactoring wish list

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#531]
How do you wanna see the code base refactored. Add your ideas here.

**Comment by superseacat** [comment]
- [ ] replace concurrent installation of components (like learning modules) with the sequential approach, simplify
- [ ] replace raw thread implementation with some `Executors` approach, in other words, delegate Thread handling to some ready-made JVM mechanism
- [ ] choose-and-use some alternative existing ForkJoin implementation

**Comment by OlliKiljunen** [comment]
Rename the project (intellij-plugin) to something more relevant.

**Comment by stellatsv** [comment]
No longer relevant.
