### ISSUE TITLE
update JUnit to the latest (5.x)

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/aplus-courses#553]
as suggested during one of the discussion (on how to please Sonar), the idea of updating to JUnit5 was born: https://github.com/Aalto-LeTech/intellij-plugin/pull/548#issuecomment-781895524

**Comment by stellatsv** [comment]
Check how easy it will be (possibly automated)

**Comment by stellatsv** [comment]
Hello @tulikavijay, thank you for your growing interest in our project. Feel free to try out this method for migrating and make a PR if it goes well.
