### ISSUE TITLE
Local History Tags

### ISSUE THREAD

**Issue by stellatsv** [Aalto-LeTech/aplus-courses#635]
- Check if they work
- Change the colours

**Comment by stellatsv** [comment]
Students can download their own submissions using the assistant mode, so this might not be needed anymore.
For now: just check if it works - if it does, leave it alone; if it doesn't, consider fixing or removing altogether.

**Comment by Taikelenn** [comment]
![obraz](https://user-images.githubusercontent.com/73069541/142080577-f5fddc69-3bd7-4acd-8039-7fb16c435df6.png)
It still works

**Comment by jaakkonarhi** [comment]
wont fix

**Comment by Taikelenn** [comment]
Nobody uses it anyway
