### ISSUE TITLE
Modifiable VM options to fix encoding issues

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#750]
Some students (Mac users?) are observing character encoding issues concerning Scandinavian letters (Åå, Ää, Öö) at least in the REPL. The suggested fix is to add some JVM parameters in **Help->Edit Cutom VM Options...** (ask Juha if you don't know what should be added there). This modification of parameters should be done automatically by the plugin (and perhaps be configured in the course file -- consider different possibilities!).

**Comment by Taikelenn** [comment]
See `com.intellij.diagnostic.VMOptions` for a nice interface that can add stuff
