### ISSUE TITLE
Download past exercise submissions while downloading student submission

### ISSUE THREAD

**Issue by jaakkonakaza** [Aalto-LeTech/aplus-courses#781]
Some assignments don't have all of the necessary files for running the program, such as the FlappyBug assignments, so downloading the past assignments from first to last could solve this

**Comment by OlliKiljunen** [comment]
Ideally: option to download either
- student's previous submission
- example solution (from CodeVault?)
These should be specified in course config file

**Comment by OlliKiljunen** [comment]
Too complex, not that useful.
