### ISSUE TITLE
Clean up the wiki

### ISSUE THREAD

**Issue by Taikelenn** [Aalto-LeTech/aplus-courses#787]
Review and delete irrelevant wiki entries - most of them are outdated, and the wiki is where the documentation will go. "Meeting minutes", "Idea board" etc. should be IMO removed.
Also, keep in mind that the wiki is public. Not that it matters, but someday someone might look there and instead of finding documentation, they'll find meeting history from January 2020 and links to Eclipse configuration files :p

**Comment by stellatsv** [comment]
Either move the old entries to the Archive or delete them altogether.

**Comment by Taikelenn** [comment]
![obraz](https://user-images.githubusercontent.com/73069541/145211357-d362689c-8422-4e81-8387-3f2c2832c649.png)
I suggest deleting all entries marked with a red X. I don't see any reason they should stay there, and it's difficult to distinguish some of these "old sprint logs" from actual documentation.

**Comment by OlliKiljunen** [comment]
@Taikelenn Feel free to remove those. I learned that [GitHub wikis can be cloned as git repos](https://stackoverflow.com/questions/18759738/effortless-export-from-github-wiki) so the deleted information should stay available that way. Furthermore, I took a backup copy of that wiki repo to my computer. So let it go!

**Comment by Taikelenn** [comment]
Done
