### ISSUE TITLE
Optional tasks are not marked correctly in O1 2021

### ISSUE THREAD

**Issue by Taikelenn** [Aalto-LeTech/aplus-courses#800]
![obraz](https://user-images.githubusercontent.com/73069541/141010548-b2d5fee6-387f-4f11-a43e-d62c18552baa.png)
This is how optional tasks look now. The plugin detects them using `if (exercise.getMaxSubmissions() == 0 && exercise.getMaxPoints() == 0)` which might have worked in the past, but in O1 2021 it does not.
Investigate whether that's intentional, and update the optional assignment detection criteria if necessary.

**Comment by OlliKiljunen** [comment]
The task for this issue is to fix the problem in an ad hoc manner for O1. For a proper solution, see #801.
