### ISSUE TITLE
Recognize optional tasks based on categories

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#801]
The assignments in A+ (may) have teacher-defined categories such as "training". Those categories should be used to determine if an assignment is optional or not (or more generally, how the assignments are shown in the assignment tree - think about different possibilities).

Solution should be something like this: teacher declares in the course config file the categories that are considered optional. Then, assignments of these categories are shown as optional and others are not.

Currently, optional assignments are recognized based on some fuzzy rules that doesn't always work.

**Comment by Taikelenn** [comment]
The plugin state after #800 is merged is that an assignment is optional if its category is "training" or "challenge" (the latter is for backwards compatibility with O1).
We can either do the thing described in the issue OR introduce an informal (or formal, documented) consensus that optional tasks always have the category "training". Shouldn't be difficult given that there are currently only two courses that use the plugin, and it would absolve us from actually having to do anything.

(I'm doing everything to prevent the introduction of yet another parameter to the Course's constructor)
