### ISSUE TITLE
Static file URLs changing

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#812]
Juha @ Slack:
>On Jan 3rd, there will be an A+ update, which will include a change in where plus.cs.aalto.fi accesses static course materials. Previously, they have been stored on grader.cs.aalto.fi, but in the future, they will be on gitmanager.cs.aalto.fi. Since the course URLs are still hardcoded, I expect this will break the plugin, no? However, EDIT has promised to set up redirects from the old domain to the new if we request them. Assuming we need such redirects, could someone from the dev team contact **[aplusguru at cs aalto fi]** with the precise details?

The following must be done
- [x] check whether the plugin can handle HTTP redirects
- [x] check if redirecting course config file URL is enough for module URLs to be updated
- [x] contact aplusguru and request redirs

**Comment by Taikelenn** [comment]
Redirects work nicely. An e-mail has been sent to gurus

**Comment by Taikelenn** [comment]
Redirects are now working.
