### ISSUE TITLE
Add a “Relaunch REPL and run all of the previous session’s commands” button.     

### ISSUE THREAD

**Issue by stellatsv** [Aalto-LeTech/aplus-courses#821]
Basically, the same feature that Eclipse’s Scala IDE (R.I.P.) has.

**Comment by stellatsv** [comment]
Let's try to contact JetBrains about it?

**Comment by OlliKiljunen** [comment]
@Taikelenn: The current implementation supports auto-executing code in the REPL. How to design the UI, is non-trivial.

@jaakkonakaza: User could store a state when using a REPL and then return to that later.

**Comment by jaakkonakaza** [comment]
Moved to https://github.com/Aalto-LeTech/REPLace/issues/1
