### ISSUE TITLE
New code style warnings

### ISSUE THREAD

**Issue by stellatsv** [Aalto-LeTech/aplus-courses#824]
* E.g., “don’t use `Option.get`”, “don’t omit `this`”, etc.
* Customizable by course at least. And perhaps also by module!
* IntelliJ inspections

**Comment by stellatsv** [comment]
Investigate how we could do this.

**Comment by OlliKiljunen** [comment]
Result of the investigation: not worth it. Use some existing linter instead (maybe specify that in course config file).
