### ISSUE TITLE
Language variants (en/fi) of modules 

### ISSUE THREAD

**Issue by stellatsv** [Aalto-LeTech/aplus-courses#825]
* Course config can mark modules as being different language-variants (e.g., Finnish and English) of each other. 
* This is reflected in the UI somehow (perhaps by graying out and textually marking any other variants of module that the user has already downloaded).

**Comment by jaakkonakaza** [comment]
```json
{
  "name": "Aliohjelmia",
  "url": 
  "https://gitmanager.cs.aalto.fi/static/O1_2024/modules/given/Aliohjelmia/Aliohjelmia.zip",
  "language": "fi",
  "version": "1.0",
  "changelog": ""
},
```

The language of each module can now optionally be set in the config. It is shown in the modules list. The assignments are linked to the module of the correct language
