### ISSUE TITLE
Problem with Scala 3 dependencies

### ISSUE THREAD

**Issue by jaakkonakaza** [Aalto-LeTech/aplus-courses#845]
Seems like dependencies in a Scala 3 project aren't inherited from parent modules

**Comment by OlliKiljunen** [comment]
Do we know if this is a bug, a design decision, or an option that can be changed?

**Comment by OlliKiljunen** [comment]
Is someone working with this? Please, add yourself as an assignee.

**Comment by jaakkonarhi** [comment]
Seems like this is fixed in in the current IntelliJ/Scala versions

**Comment by stellatsv** [comment]
@jaakkonarhi test this
