### ISSUE TITLE
Consider a dedicated IntelliJ project generator template

### ISSUE THREAD

**Issue by Taikelenn** [Aalto-LeTech/aplus-courses#867]
![obraz](https://user-images.githubusercontent.com/73069541/159599290-9d01a3fb-a902-4c85-8851-dde5fa359b37.png)
Consider whether it's worth adding a dedicated "A+ Courses" project template in the IntelliJ's "New project" window, in the section marked on the screenshot above.

Note that it wouldn't actually do anything special, it would be the same thing as a generic, empty, module-less project. However it might make users less confused, especially that now there's a difference between "New project" and "Empty project".

**Comment by stellatsv** [comment]
Demonstrate in the next weekly, and make the decision whether or not we want this.
