### ISSUE TITLE
The REPL prompt shows up too late

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#889]
Juha: the `scala>` prompt shows up too late

(Olli: does it happen only once in the beginning or after each execution)

**Comment by Taikelenn** [comment]
https://youtrack.jetbrains.com/issue/SCL-20177/Scala-3-REPL-prompt-%22scala%3E%22-appears-only-after-the-first-line-i

**Comment by stellatsv** [comment]
Waiting for a response from JetBrains. Check again towards the start of the semester!

**Comment by stellatsv** [comment]
Check the situation at the end of June, and make the decision what to do.

**Comment by OlliKiljunen** [comment]
Seems to work in the "runIde" Gradle task (I don't think it worked before), investigate further
