### ISSUE TITLE
Character encoding issue in Scala 3 REPL

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#890]
Related to the Scala 3 REPL

Juha: UTF-8 ("äö") surprisingly did not work for me in the REPL until I adjusted VM options — I don’t recall having had to do that on Windows before, but I could be mistaken (Anyway, this was in a non-A+-courses project. I guess it should work for students.)

**Comment by Taikelenn** [comment]
By default it doesn't work in Scala 2 REPL either

**Comment by Taikelenn** [comment]
Adding `-Dfile.encoding=UTF-8` to VM options seems to solve the problem, both in Scala 2 and 3. This could be added to the course configuration file.

**Comment by Taikelenn** [comment]
Adding the aforementioned option solves the problem
