### ISSUE TITLE
Create a visual designer for tutorials

### ISSUE THREAD

**Issue by Taikelenn** [Aalto-LeTech/aplus-courses#894]
Writing JSON by hand to create tutorials is quite cumbersome, especially for people who are not familiar with the implementation details of tutorials. Therefore, it would probably be nice to have a simple, graphical designer for tutorials with several features:
- loading and saving tutorials as JSON files
- moving back and forth between tutorial steps
- adding/removing a selected step
- editing step metadata (popup title, description, action, highlighted components etc.)
- editing action parameters (each action is different, e.g. for "open file" we'll be able to edit the filename; for "open REPL" - module name)
- being cross-platform (at least Windows & Mac OS)
- (nice to have) a preview of the IDE with highlighted components (just a static screenshot with hardcoded x/y coordinates for each highlightable component)

Olli and I have come up with this example design - https://i.imgur.com/Ep1FS3b.png - which might be followed as the design for the final product. However, if you have a better design in mind, feel free to implement it your own way!

A possible implementation would be a webpage (HTML + Javascript), preferably without backend. This way, we could use something like Github Pages to host this for free, and the users wouldn't need to update the tool when we inevitably update it with new actions/components. Alternatively, a Java GUI application will work well, too.

**Comment by jaakkonakaza** [comment]
https://github.com/Aalto-LeTech/aplus-courses-tutorial-builder
