### ISSUE TITLE
Better course changing

### ISSUE THREAD

**Issue by jaakkonakaza** [Aalto-LeTech/aplus-courses#901]
Now if you wanna change course for example from O1 2021 to O1 2022 you have to use the Reset A+ Project action, which removes the course config and all the info about modules. A better approach would be to edit the course url in the course config

**Comment by stellatsv** [comment]
How do these 2 approaches differ in functionality?

**Comment by OlliKiljunen** [comment]
This should be paid attention in semi-near future. The current user workflow is bad.
