### ISSUE TITLE
Custom REPL

### ISSUE THREAD

**Issue by Taikelenn** [Aalto-LeTech/aplus-courses#905]
Do some preliminary research: what would it take to make a custom REPL (i.e. not dependant on the current REPL; a separate implementation) and what features would it have.

**Comment by jsorva** [comment]
A related thing to investigate is whether integrating Ammonite REPL might be a) feasible; b) beneficial.

**Comment by Taikelenn** [comment]
Here are my findings so far:
If we want to retain the functionality that IntelliJ offers, then writing a custom REPL (from scratch) is actually plenty of work. There are many obvious features that are non-trivial to implement. Some of them include:
- syntax highlighting
- autocomplete
- custom run configurations
- correct "line folding"
- reimplementing the visual part (implementing a terminal, handling multiple REPLs at once, handling REPL debugging)
- inter-process communication (making sure it works on all major operating systems, handling errors)
- supporting both Scala 2 and 3
- probably many more...

And this is just reimplementing the currently existing functionality; adding new is a whole another story.

IntelliJ provides a "ready, bare-bones REPL" in the class `LanguageConsoleImpl` (2000+ lines of code + dependencies), which the Scala plugin inherits from in order to provide its own REPL. Unfortunately, using this class gives us little customizability - we'll end up in the same situation as we're now. I don't think there's a way around that.

Unless there's a way around reimplemeting all these features while maintaining customizability (I don't think there is), I believe we should abandon this idea. It'd be more efficient to just find a way to add our desired features on top of the existing REPL, or in the worst-case scenario, convince ourselves that "we don't really need these features".

(PS: Integrating Ammonite REPL (or any other REPL, for that matter) is not particularly feasible - it's a standalone application (from what I see), strictly coupled with a standalone terminal, not particularly embeddable.)

**Comment by OlliKiljunen** [comment]
Urgent issues fixed; closing this for now as unimportant.
