### ISSUE TITLE
Don't show the group selection if the course doesn't have groups

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#963]
When submitting an exercise, there's this drop-down list for group selection. In some cases, there is only one option: "submit alone", but the user has to still explicitly choose that (at the first time at least, then they can make it default). It depends on the situation whether this behavior is what we want:
1. in courses that have group-submission option (such as O1), it might be a good reminder for non-group-working students of the possibility of working in groups.
2. in courses that doesn't support group submissions it is nothing but an annoyance.

So, the decision whether to show a no-choice drop-down list should perhaps be based on whether the course have group submissions or not. This information should probably be included in the course config file (defaulting to "yes").

Discuss with the teachers first.

**Comment by Taikelenn** [comment]
Potential alternative solution: if the only option is "submit alone", set this option by default and disable the groupbox

**Comment by jaakkonakaza** [comment]
Submit alone is the default group. A course can set alwaysShowGroups to true in the config, in which case the group selector will always be shown. Else it is only shown if the user has any groups
