### ISSUE TITLE
In O1, week 1 shows closed for some reason

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#974]
Take a look at the API results at https://plus.cs.aalto.fi/api/v2/courses/249/exercises/

`/results/0/is_open` is false while e.g. `/results/1/is_open` is true. This makes no sense. If this can't be fixed in A+ side, consider fixing it in the plugin.

**Comment by jsorva** [comment]
I discussed this with Pasi, and we confirmed there’s something weird going on. I believe the A+ folks will take a look at it.

**Comment by jsorva** [comment]
This seems to have been fixed: https://github.com/apluslms/a-plus/issues/1107
