### ISSUE TITLE
Auto-install JDK

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#977]
When a course is linked. JDK (or Python runtime) should be defined in the course config file. Reuse IntelliJ platform code if possible.

**Comment by Taikelenn** [comment]
Alternatively, we can piggyback on the new feature introduced in IntelliJ 2023.1: selecting JDK in project creation window:
![img](https://github.com/Aalto-LeTech/aplus-courses/assets/73069541/64060f23-de9e-4395-942d-90486d3dca8f)
